import cv2 as cv
from matplotlib import pyplot as plt
import numpy as np
if __name__=='__main__':
    img1=cv.imread('test.png')
    gray1=cv.cvtColor(img1, cv.COLOR_BGR2GRAY)
    img2=cv.imread('test2.jpeg')
    gray2=cv.cvtColor(img2, cv.COLOR_BGR2GRAY)
    ax1=plt.subplot(2,4,1)
    ax1.imshow(gray1,'gray')
    ax1.set_title('img1')
    ax1=plt.subplot(2,4,5)
    ax1.imshow(gray2,'gray')
    ax1.set_title('img2')

    f=np.fft.fft2(gray1)
    fangle=np.angle(f)
    f=np.fft.fftshift(f)
    fmagnitude=np.log(np.abs(f))
    ax1=plt.subplot(2,4,2)
    ax1.imshow(fmagnitude,'gray')
    ax1.set_title('img1_magnitude')
    ax1=plt.subplot(2,4,3)
    ax1.imshow(fangle,'gray')
    ax1.set_title('img1_angle')

    f2=np.fft.fft2(gray2)
    fangle2=np.angle(f2)
    f2=np.fft.fftshift(f2)
    fmagnitude2=np.log(np.abs(f2))
    ax1=plt.subplot(2,4,6)
    ax1.imshow(fmagnitude2,'gray')
    ax1.set_title('img2_magnitude')
    ax1=plt.subplot(2,4,7)
    ax1.imshow(fangle2,'gray')
    ax1.set_title('img2_angle')

    j=complex(0,1)
    f1=np.abs(f)*np.cos(fangle2)+j*np.abs(f)*np.complex64(np.sin(fangle2))
    f1=np.fft.ifftshift(f1)
    f1=np.fft.ifft2(f1)
    f1=np.abs(f1)
    ax1=plt.subplot(2,4,4)
    ax1.imshow(f1,'gray')

    j=complex(0,1)
    f1=np.abs(f2)*np.cos(fangle)+j*np.abs(f2)*np.complex64(np.sin(fangle))
    f1=np.fft.ifftshift(f1)
    f1=np.fft.ifft2(f1)
    f1=np.abs(f1)
    ax1=plt.subplot(2,4,8)
    ax1.imshow(f1,'gray')

    plt.show()